services:
  lpb:
    image: ghcr.io/williamjacksn/license-plate-bingo
    init: true
    ports:
      - 8080:8080
    volumes:
      - ./:/home/python/license-plate-bingo

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/williamjacksn/license-plate-bingo
    init: true
    volumes:
      - ./:/home/python/license-plate-bingo
    working_dir: /home/python/license-plate-bingo
