services:
  lpb:
    image: ghcr.io/williamjacksn/license-plate-bingo
    init: true
    ports:
      - 8080:8080
    volumes:
      - ./:/app

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/williamjacksn/license-plate-bingo
    init: true
    volumes:
      - ./:/app
